apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      nodePort: 30007
      targetPort: 8080
      port: 8080
