apiVersion: v1
kind: Service
metadata:
  name: whiteboard-service
spec:
  selector:
    app: whiteboard
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
  type: NodePort

