apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whiteboard
  template:
    metadata:
      labels:
        app: whiteboard
    spec:
      containers:
      - name: whiteboard-app
        image: corpsbliss/whiteboard_hub:6343606
        ports:
        - containerPort: 5000
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_HOST
          value: "redis-service"
        volumeMounts:
        - name: notes-volume
          mountPath: /whiteboard_app/notes
      volumes:
      - name: notes-volume
        persistentVolumeClaim:
          claimName: uploads-pvc

